---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Stale Pull Requests

# After 30 days of no activity on a PR, the PR should be marked as stale,
# a comment made on the PR informing the author of the new status,
# and closed after 15 days if there is no further activity from the change to stale state.
on:
  schedule:
    - cron: '30 1 * * *'  # run every day

permissions: {}

jobs:
  stale-auto-close:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639  # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: "This pull request is stale because it has been open 30 days with no activity. Make a comment or update the PR to avoid closing PR after 15 days."
          days-before-pr-stale: 30
          days-before-pr-close: 15
          remove-pr-stale-when-updated: 'true'
          close-pr-message: 'This pull request was automatically closed due to inactivity'
